[package]
name = "gpu-simple"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { git = "https://github.com/aarch64-switch-rs/nx" }
ui2d = { path = "../ui2d" }

[package.metadata.nx.nro]
nacp = { name = "gpu-simple", author = "XorTroll", version = "Example" }