[package]
name = "dir-list"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2021"

[dependencies]
nx = {  workspace = true, features = [ "input", "gpu", "fs" ] }

[package.metadata.nx.nro]
nacp = { default_name = "dir-list", default_author = "XorTroll", version = "Example" }