[package]
name = "fs-api"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { git = "https://github.com/aarch64-switch-rs/nx" }

[package.metadata.nx.nro]
nacp = { name = "fs-api", author = "XorTroll", version = "Example" }