[package]
name = "file-rw"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2021"

[dependencies]
nx = {  workspace = true, features = [ "fs" ] }

[package.metadata.nx.nro]
nacp = { default_name = "file-rw", default_author = "XorTroll", version = "Example" }