[package]
name = "libapplet-launch"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { git = "https://github.com/aarch64-switch-rs/nx" }

[package.metadata.sprinkle.nro]
nacp = { name = "libapplet-launch", author = "XorTroll", version = "Example" }