[package]
name = "libapplet-launch"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2021"

[dependencies]
nx = { workspace = true, features = [ "services" ] }

[package.metadata.nx.nro]
nacp = { default_name = "libapplet-launch", default_author = "XorTroll", version = "Example" }